const express = require("express");
const Post = require("../model/Post");
require("../DB/db");
const router = express.Router();


router.post("/Create_Post", async (req, res) => {
  console.log(req.body);
  const {
    ProductName,
    Cardslot,
    Internalmemory,
    Technology,
    G2Bands,
    G3Bands,
    G4Bands,
    Networkspeed,
    Announceddate,
    Status,
    Dimensions,
    Weight,
    Sim,
    Othersbody,
    displaysize,
    displaytype,
    displayresolution,
    displayprotection,
    OS,
    chipset,
    CPU,
    GPU,
    Primarycamera,
    Secondarycamera,
    camerafeatures,
    cameravideo,
    cameraothers,
    Loudspeaker,
    jacksound,
    commswlan,
    commsbluetooth,
    commsGPS,
    commsNFC,
    commsradio,
    commsusb,
    Sensors,
    batterytype,
    batteryothers,
    description,
    Productprice,
    rupeePrice,
    dollarPrice,
    darazLink,
    amazonLink,
    pticeoyeLink,
  } = req.body;
  const postRes = new Post({
    ProductName,
    Cardslot,
    
    Internalmemory,
    Technology,
    G2Bands,
    G3Bands,
    G4Bands,
    Networkspeed,
    Announceddate,
    Status,
    Dimensions,
    Weight,
    Sim,
    Othersbody,
    displaysize,
    displaytype,
    displayresolution,
    displayprotection,
    OS,
    chipset,
    CPU,
    GPU,
    Primarycamera,
    Secondarycamera,
    camerafeatures,
    cameravideo,
    cameraothers,
    Loudspeaker,
    jacksound,
    commswlan,
    commsbluetooth,
    commsGPS,
    commsNFC,
    commsradio,
    commsusb,
    Sensors,
    batterytype,
    batteryothers,
    description,
    Productprice,
    rupeePrice,
    dollarPrice,
    darazLink,
    amazonLink,
    pticeoyeLink,
  });
  const result = await postRes.save();
  console.log(result);
});
module.exports = router;
